# configuration for ESKAPADE development machine with provisioned image
Vagrant.configure("2") do |config|
  # base box: ESKAPADE dev box
  config.vm.box = "kave/eskapade-dev"

  # forward port for Jupyter notebooks
  config.vm.network "forwarded_port", guest: 8888, host: 8889

  # VirtualBox settings
  config.vm.provider "virtualbox" do |vb|
    # basic settings
    vb.name = "eskapade-dev"
    #vb.memory = "8192"
    #vb.cpus = 4

    # graphics memory
    #vb.customize ["modifyvm", :id, "--vram", "256"]

    # display the VirtualBox GUI when booting the machine
    #vb.gui = true
  end

  # mounts
  config.vm.synced_folder "../..", "/opt/eskapade", id: "esrepo"

  # mount ESKAPADE repository
  config.vm.provision "shell", path: "mount.sh", run: "always"

  # install ESKAPADE (when starting with clean instance)
  config.vm.provision "shell", path: "pip.sh", run: "once"

  # login 
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.ssh.insert_key = false

end
