from distutils.core import setup

setup(
      name='Eskapade',
      version='0.6',
      description='Eskapade modular analytics',
      author='KPMG',
      url='http://eskapade.kave.io',
      packages=['eskapade',
                'eskapade.analysis',
                'eskapade.analysis.links',
                'eskapade.core',
                'eskapade.core_ops',
                'eskapade.core_ops.links',
                'eskapade.data_quality',
                'eskapade.data_quality.links',
                'eskapade.root_analysis',
                'eskapade.root_analysis.decorators',
                'eskapade.root_analysis.links',
                'eskapade.visualization',
                'eskapade.visualization.links',
               ],
      package_dir={'': 'python', 
                   'eskapade': 'python/eskapade',
                   'analysis': 'python/eskapade/analysis',
                   'core': 'python/eskapade/core',
                   'core_ops': 'python/eskapade/core_ops',
                   'data_quality': 'python/eskapade/data_quality',
                   'root_analysis': 'python/eskapade/root_analysis',
                   'visualization': 'python/eskapade/visualization',
                   }
)
