#! /bin/bash

# source KAVE environment
if [ -f /opt/KaveToolbox/pro/scripts/KaveEnv.sh ]; then
    source /opt/KaveToolbox/pro/scripts/KaveEnv.sh
fi

# useful aliases
alias jupy='nohup jupyter notebook --port 8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=\"\"'
alias gitlog='git log --graph --decorate --oneline'
